name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    -
      name: Login to Aliyun Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: imbrook
        password: ${{ secrets.ALI_DOCKER_TOKEN }}
    - name: Build the Docker image
      run: docker build . --file alpine/Dockerfile.compress --tag registry.cn-hangzhou.aliyuncs.com/17ch/flowise:main
    - name: Publish
      run: docker push registry.cn-hangzhou.aliyuncs.com/17ch/flowise:main
