name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: production

    steps:
    - uses: actions/checkout@v4
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - 
      name: Pull flowise
      run: docker pull flowiseai/flowise:2.0.2
    -
      name: Login to Aliyun Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: imbrook
        password: ${{ secrets.ALI_DOCKER_TOKEN }}
    - name: Push
      run: |
        docker tag flowiseai/flowise:2.0.2 registry.cn-hangzhou.aliyuncs.com/17ch/flowise:2.0.2
        docker push registry.cn-hangzhou.aliyuncs.com/17ch/flowise:2.0.2
